[package]
name = "kude"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
x11rb = "0.13.1"

[[bin]]
name = "main"
path = "src/main.rs"

[[bin]]
name = "taskbar"
path = "src/taskbar.rs"
